In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv(r"C:\Users\ADITYA\Downloads\cgpa_vs_package.csv")
df

CGPA  Package (Lacs)
0    6.87           12.64
1    9.75           16.55
2    8.66           15.41
3    7.99           14.08
4    5.78           11.03
..    ...             ...
995  5.46            9.43
996  9.59           18.27
997  5.68            8.46
998  9.75           17.65
999  7.23           13.93

[1000 rows x 2 columns]

In [11]:
# checking that the dataset conatins null values or not
df.isnull().sum()

CGPA              0
Package (Lacs)    0
dtype: int64

In [12]:
# checking for duplicated value
df.duplicated().sum()

3

In [14]:
# dropping the duplicates
df.drop_duplicates(inplace=True)
df

CGPA  Package (Lacs)
0    6.87           12.64
1    9.75           16.55
2    8.66           15.41
3    7.99           14.08
4    5.78           11.03
..    ...             ...
995  5.46            9.43
996  9.59           18.27
997  5.68            8.46
998  9.75           17.65
999  7.23           13.93

[997 rows x 2 columns]

In [24]:
import plotly_express as px
fig = px.histogram(df, x='CGPA')
fig.update_traces(marker_line_color="black", marker_line_width=1)
fig.show()

In [28]:
df['CGPA'].describe()

count    997.000000
mean       7.451344
std        1.461684
min        5.020000
25%        6.190000
50%        7.480000
75%        8.730000
max       10.000000
Name: CGPA, dtype: float64

In [26]:
fig = px.histogram(df, x='Package (Lacs)')
fig.update_traces(marker_line_color="black", marker_line_width=1)
fig.show()

In [27]:
df['Package (Lacs)'].describe()

count    997.000000
mean      12.565125
std        2.649992
min        6.630000
25%       10.400000
50%       12.410000
75%       14.720000
max       19.280000
Name: Package (Lacs), dtype: float64

In [33]:
px.box(df, 'CGPA')

In [34]:
px.box(df, 'Package (Lacs)')

In [38]:
px.scatter(df, 'CGPA', 'Package (Lacs)')

In [42]:
# extract the X, y features
X, y = df.loc[:, "CGPA"].values, df.loc[:, "Package (Lacs)"].values
X

array([ 6.87,  9.75,  8.66,  7.99,  5.78,  5.78,  5.29,  9.33,  8.01,
        8.54,  5.1 ,  9.85,  9.16,  6.06,  5.91,  5.92,  6.52,  7.62,
        7.16,  6.46,  8.06,  5.7 ,  6.46,  6.83,  7.28,  8.93,  6.  ,
        7.57,  7.96,  5.23,  8.04,  5.85,  5.33,  9.74,  9.83,  9.04,
        6.52,  5.49,  8.42,  7.2 ,  5.61,  7.48,  5.17,  9.55,  6.29,
        8.31,  6.56,  7.6 ,  7.73,  5.92,  9.85,  8.88,  9.7 ,  9.47,
        7.99,  9.61,  5.44,  5.98,  5.23,  6.63,  6.94,  6.36,  9.14,
        6.78,  6.4 ,  7.71,  5.7 ,  9.01,  5.37,  9.93,  8.86,  5.99,
        5.03,  9.08,  8.53,  8.65,  8.86,  5.37,  6.79,  5.58,  9.32,
        8.12,  6.65,  5.32,  6.55,  6.63,  8.65,  8.19,  9.44,  7.36,
        5.6 ,  8.57,  8.8 ,  7.81,  8.85,  7.47,  7.61,  7.14,  5.13,
        5.54,  5.16,  8.18,  6.57,  7.54,  9.54,  6.25,  7.05,  8.78,
        6.14,  5.38,  6.45,  5.81,  9.65,  9.04,  8.17,  9.36,  9.02,
        5.93,  9.46,  7.7 ,  9.04,  9.48,  6.59,  5.55,  6.14,  7.14,
        9.09,  9.3 ,

In [43]:
y

array([12.64, 16.55, 15.41, 14.08, 11.03, 10.8 ,  8.46, 16.36, 11.97,
       14.33,  9.41, 16.73, 15.88, 10.  , 11.09,  9.9 , 10.52, 13.73,
       10.66, 11.39, 12.54, 10.88, 10.62, 11.64, 12.68, 13.12,  9.46,
       13.8 , 14.28,  9.1 , 12.2 , 10.44,  9.7 , 16.46, 17.79, 14.55,
       10.48,  6.77, 15.11, 12.45,  7.77, 10.85,  7.84, 16.89, 10.3 ,
       13.2 , 10.05, 11.76, 11.09,  8.77, 15.53, 15.65, 16.18, 15.13,
       15.77, 15.53, 10.33, 11.7 ,  7.24, 11.25, 11.18, 10.12, 15.96,
       10.8 , 10.29, 12.82,  9.23, 14.01,  9.85, 17.78, 15.27,  9.72,
        7.77, 14.6 , 16.73, 15.51, 14.09,  9.21, 11.08,  9.99, 16.25,
       14.77, 10.36,  9.07,  9.29,  9.92, 15.46, 12.85, 15.07, 12.39,
       10.13, 13.38, 11.35, 12.29, 16.12, 12.93, 14.15, 10.9 ,  7.01,
        9.8 ,  8.94, 14.09, 12.  , 13.13, 16.48, 11.25, 12.38, 15.65,
       11.36, 10.6 , 10.22, 10.27, 15.89, 14.4 , 13.08, 16.27, 15.62,
       10.39, 15.72, 12.98, 16.05, 14.49, 11.13,  9.44, 11.1 , 10.68,
       16.81, 15.89,

In [44]:
# perform train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
len(X_train)

797

In [47]:
len(X_test)

200

In [139]:
# Implementing our Simple Linear Regression class
class Simple_Linear_Regression:
    def __init__(self, coef_=None, intercept_=None):
        self.coef_ = coef_
        self.intercept_= intercept_
    def fit(self, X_train, y_train):
        x_mean, y_mean = np.mean(X_train), np.mean(y_train)
        self.coef_ = np.dot((y_train - y_mean), (X_train - x_mean)) / np.dot((X_train - x_mean), (X_train - x_mean))
        self.intercept_ = y_mean - self.coef_ * x_mean
    def predict(self, X_test):
        return self.coef_ * X_test + self.intercept_
    def get_params(self, deep):
        return {"coef_" : self.coef_, "intercept_" : self.intercept_}

In [140]:
slr = Simple_Linear_Regression()

In [141]:
slr.fit(X_train, y_train)

In [142]:
print(slr.coef_)
print(slr.intercept_)

1.6785565181568336
0.09418827082442682


In [143]:
y_pred = slr.predict(X_test)

In [144]:
y_pred

array([16.09083189, 13.62335381,  9.82981608, 10.75302216, 11.64265712,
       12.6162199 , 16.44332876, 11.49158703,  9.09125121, 11.82729833,
        8.63804095, 12.24693746, 13.18692911,  9.22553573, 14.54655989,
       14.96619902, 11.82729833, 10.36695416, 13.75763833,  8.53732756,
       12.80086111,  8.68839764,  8.60446982,  8.72196877,  8.70518321,
       11.22301799,  8.82268217, 15.65440719,  9.44374808, 11.82729833,
       12.46514981,  9.79624495, 11.57551486, 10.40052529, 11.59230042,
       10.51802425, 10.48445312, 15.9397618 , 13.57299711,  9.93052947,
       12.36443642,  9.47731921,  9.47731921, 13.10300129, 15.03334128,
        9.72910269, 14.34513311, 11.77694164, 14.96619902, 16.42654319,
        9.39339138, 11.96158285, 10.60195207, 11.55872929, 13.58978268,
       13.62335381,  8.65482651,  9.5780326 , 13.57299711, 12.36443642,
       13.50585485,  8.92339556, 10.75302216,  8.87303886, 11.18944686,
        8.63804095, 15.38583815,  9.86338721, 13.65692494,  8.65

In [145]:
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

In [146]:
mae = mean_absolute_error(y_test, y_pred)
mse = root_mean_squared_error(y_test, y_pred) ** 2
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
adj_r2 =((1-r2)*(len(X_test)-1)) / (len(X_test)-1-1)

print(f"MAE : {mae}")
print(f"MSE : {mse}")
print(f"RMSE : {rmse}")
print(f"R2 Score : {r2}")
print(f"Adjusted R2 Score : {r2}")

MAE : 0.7137488876291924
MSE : 0.8050617698182979
RMSE : 0.8972523445599336
R2 Score : 0.8839510940102299
Adjusted R2 Score : 0.8839510940102299


In [147]:
# implementing sklearn linear regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train.reshape(-1, 1), y_train)
y_pred_sk = lr.predict(X_test.reshape(-1, 1))

In [148]:
mae = mean_absolute_error(y_test, y_pred_sk)
mse = root_mean_squared_error(y_test, y_pred_sk) ** 2
rmse = root_mean_squared_error(y_test, y_pred_sk)
r2 = r2_score(y_test, y_pred_sk)
adj_r2 =((1-r2)*(len(X_test)-1)) / (len(X_test)-1-1)

print(f"MAE : {mae}")
print(f"MSE : {mse}")
print(f"RMSE : {rmse}")
print(f"R2 Score : {r2}")
print(f"Adjusted R2 Score : {r2}")

MAE : 0.7137488876291921
MSE : 0.805061769818297
RMSE : 0.8972523445599332
R2 Score : 0.88395109401023
Adjusted R2 Score : 0.88395109401023


In [149]:
print(lr.coef_)
print(lr.intercept_)

[1.67855652]
0.09418827082441439


In [150]:
import plotly.graph_objects as go
fig = px.scatter(df, 'CGPA', 'Package (Lacs)')
fig.add_trace(go.Scatter(x = df['CGPA'], y = slr.predict(df['CGPA']), mode="lines", name="SLR"))
fig.add_trace(go.Scatter(x = df['CGPA'], y = lr.predict(df['CGPA'].values.reshape(-1, 1)), mode="lines", name="Sklearn SLR"))

In [155]:
# performing cross validation
from sklearn.model_selection import cross_val_score
cv_score = np.mean(cross_val_score(slr, X, y, cv=10, scoring="r2"))
cv_score_sk = np.mean(cross_val_score(lr, X.reshape(-1, 1), y, cv=10, scoring="r2"))
print(f"SLR CV Score : {cv_score}")
print(f"SKlearn LR CV Score : {cv_score_sk}")

SLR CV Score : 0.8656335541194616
SKlearn LR CV Score : 0.8656335541194616


In [156]:
# save the model
import pickle

with open('model.pkl', "wb") as file:
    pickle.dump(slr, file)